# Generated by Django 6.0.4 on 2026-04-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_id', models.CharField(max_length=100, unique=True)),
                ('centre_name', models.CharField(max_length=255)),
                ('bu_head', models.CharField(blank=True, max_length=255, null=True)),
                ('pmt_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(max_length=100)),
                ('centre_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('batch_actual_start_date', models.DateField(blank=True, null=True)),
                ('batch_actual_end_date', models.DateField(blank=True, null=True)),
                ('candidate_last_status', models.CharField(max_length=100)),
                ('assessment_certification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_actual_certification_date', models.DateField(blank=True, null=True)),
                ('placed_date', models.DateField(blank=True, null=True)),
                ('qp_name', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
        ),
        migrations.CreateModel(
            name='BatchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('centre_name', models.CharField(max_length=255)),
                ('qp', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('batch_planned_start_date', models.DateField(blank=True, null=True)),
                ('batch_planned_end_date', models.DateField(blank=True, null=True)),
                ('certification_planned_start_date', models.DateField(blank=True, null=True)),
                ('placement_planned_end_date', models.DateField(blank=True, null=True)),
                ('final_enrolment_planned', models.IntegerField(default=0)),
                ('final_certification_planned', models.IntegerField(default=0)),
                ('final_placement_planned', models.IntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.centre', to_field='centre_id')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('name_place', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('phone_hours', models.CharField(blank=True, max_length=255)),
                ('centre_name', models.CharField(blank=True, max_length=255)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
        ),
        migrations.CreateModel(
            name='HyperlocalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('discovered_employer', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('employer_address', models.TextField(blank=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('naps_eligible', models.CharField(blank=True, max_length=10)),
                ('suitable_roles', models.CharField(blank=True, max_length=500)),
                ('outreach_status', models.CharField(blank=True, max_length=100)),
                ('centre_name', models.CharField(blank=True, max_length=255)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=255)),
                ('official_email', models.CharField(max_length=255)),
                ('employee_status', models.CharField(max_length=50)),
                ('sub_project_name', models.CharField(max_length=255)),
                ('sub_project_code', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('center_name_ops', models.CharField(max_length=255)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
        ),
    ]
