# Generated by Django 6.0.5 on 2026-05-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_centre_cluster_napseligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAHIDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, db_index=True, max_length=255)),
                ('existing_potential', models.CharField(blank=True, max_length=50)),
                ('demand_city', models.CharField(blank=True, db_index=True, max_length=255)),
                ('cluster', models.CharField(blank=True, db_index=True, max_length=255)),
                ('existing_client', models.CharField(blank=True, db_index=True, max_length=500)),
                ('client_nature', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('hc', models.IntegerField(blank=True, null=True)),
                ('monthly_demand', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAHIClusterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahi_cluster_name', models.CharField(db_index=True, max_length=255)),
                ('center_name', models.CharField(blank=True, max_length=255)),
                ('centre_id_str', models.CharField(db_index=True, max_length=100)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
            options={
                'indexes': [models.Index(fields=['sahi_cluster_name', 'centre_id_str'], name='dashboard_s_sahi_cl_259b18_idx')],
            },
        ),
    ]
