# Generated by Django 6.0.5 on 2026-05-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sahidemand_sahiclustermap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiliserTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_fy', models.CharField(blank=True, max_length=50)),
                ('project_name_sahi', models.CharField(blank=True, max_length=255)),
                ('mobiliser_id', models.IntegerField(db_index=True)),
                ('sahi_center_name', models.CharField(blank=True, max_length=255)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('mobiliser_name', models.CharField(blank=True, max_length=255)),
                ('e_target', models.IntegerField(default=0)),
                ('c_target', models.IntegerField(default=0)),
                ('p_target', models.IntegerField(default=0)),
                ('e_act', models.IntegerField(default=0)),
                ('target_month_label', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sahi_center_name', models.CharField(blank=True, max_length=255)),
                ('project_name_sahi', models.CharField(blank=True, max_length=255)),
                ('sub_project_name', models.CharField(blank=True, max_length=255)),
                ('sub_project_id_1', models.CharField(blank=True, max_length=100)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('trainer_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTargetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.FloatField(default=0)),
                ('trainer_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='dashboard.trainertarget')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['trainer_target', 'date'], name='dashboard_t_trainer_4e95bb_idx')],
            },
        ),
    ]
