# Generated by Django 6.0.5 on 2026-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_mobilisertarget_trainertarget_trainertargetday'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchplan',
            name='assessment_actual_certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='batch_actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='fy_c_act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='fy_e_act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='fy_p_act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='on_going',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='placed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='projects_fy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='batchplan',
            name='sub_project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchplan',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
