# Generated by Django 6.0.5 on 2026-05-13 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_batchplan_assessment_actual_certification_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('centre_name', models.CharField(max_length=255)),
                ('sub_cluster', models.CharField(blank=True, max_length=255)),
                ('cluster', models.CharField(blank=True, max_length=255)),
                ('course_trade', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('cert_start_date', models.DateField(blank=True, null=True)),
                ('days_to_cert', models.IntegerField(blank=True, null=True)),
                ('cert_window', models.CharField(blank=True, max_length=50)),
                ('cert_target', models.IntegerField(default=0)),
                ('placement_target', models.IntegerField(default=0)),
                ('naps', models.CharField(blank=True, max_length=10)),
                ('nats', models.CharField(blank=True, max_length=10)),
                ('dbt', models.CharField(blank=True, max_length=10)),
                ('verify_flag', models.CharField(blank=True, max_length=50)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centre', to_field='centre_id')),
            ],
            options={
                'indexes': [models.Index(fields=['cert_start_date'], name='dashboard_c_cert_st_3321b4_idx'), models.Index(fields=['cert_window'], name='dashboard_c_cert_wi_151447_idx')],
            },
        ),
    ]
