# Generated by Django 6.0.5 on 2026-05-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_sourcing_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('associate_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('supply_state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('supply_district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('supply_pin', models.CharField(blank=True, db_index=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('demand_city', models.CharField(blank=True, max_length=100)),
                ('demand_cluster_client_loc', models.CharField(blank=True, max_length=255)),
                ('client', models.CharField(blank=True, db_index=True, max_length=500)),
                ('sub_cluster_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cluster', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sub_cluster', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ITIPolytechnicByPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('supply_pin', models.CharField(blank=True, db_index=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=500)),
                ('institution_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('address_location', models.CharField(blank=True, max_length=500)),
                ('distance_km', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['supply_pin', 'institution_type', 'institution_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProductivityDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('centre_name', models.CharField(blank=True, max_length=255)),
                ('centre_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('qp_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('trainer_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProductivityDurationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProductivityPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('centre_name', models.CharField(blank=True, max_length=255)),
                ('centre_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('qp_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('trainer_id', models.IntegerField(db_index=True)),
                ('enrolled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProductivityPresentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('present', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RenameIndex(
            model_name='napsdata',
            new_name='dashboard_n_batch_i_437629_idx',
            old_name='dashboard_n_batch_i_8c2b7e_idx',
        ),
        migrations.RenameIndex(
            model_name='napsplan',
            new_name='dashboard_n_centre__9c54c9_idx',
            old_name='dashboard_n_centre_eb4f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='outreachstatus',
            new_name='dashboard_o_centre__f1e8f9_idx',
            old_name='dashboard_o_centre__9d4ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='sambhavcommunity',
            new_name='dashboard_s_cluster_134601_idx',
            old_name='dashboard_s_cluster_b9f7a3_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcingactual',
            new_name='dashboard_s_communi_e0bebf_idx',
            old_name='dashboard_s_communi_e1a2bc_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcingactual',
            new_name='dashboard_s_centre__01f581_idx',
            old_name='dashboard_s_centre__d77c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcingchannelmaster',
            new_name='dashboard_s_communi_4a2870_idx',
            old_name='dashboard_s_communi_2ff03d_idx',
        ),
        migrations.AlterField(
            model_name='sourcingactual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcingchannelmaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='associatedata',
            index=models.Index(fields=['sub_cluster_id', 'supply_pin'], name='dashboard_a_sub_clu_0c8395_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedata',
            index=models.Index(fields=['cluster', 'sub_cluster'], name='dashboard_a_cluster_2b11f1_idx'),
        ),
        migrations.AddIndex(
            model_name='itipolytechnicbypin',
            index=models.Index(fields=['supply_pin', 'institution_type'], name='dashboard_i_supply__e983b3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerproductivityduration',
            index=models.Index(fields=['centre_id', 'trainer_id'], name='dashboard_t_centre__f9e259_idx'),
        ),
        migrations.AddField(
            model_name='trainerproductivitydurationday',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='dashboard.trainerproductivityduration'),
        ),
        migrations.AddIndex(
            model_name='trainerproductivitypresent',
            index=models.Index(fields=['centre_id', 'trainer_id'], name='dashboard_t_centre__62aacc_idx'),
        ),
        migrations.AddField(
            model_name='trainerproductivitypresentday',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='dashboard.trainerproductivitypresent'),
        ),
        migrations.AddIndex(
            model_name='trainerproductivitydurationday',
            index=models.Index(fields=['parent', 'date'], name='dashboard_t_parent__9fb2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerproductivitypresentday',
            index=models.Index(fields=['parent', 'date'], name='dashboard_t_parent__e7c73c_idx'),
        ),
    ]
