# Generated by Django 6.0.5 on 2026-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_centre_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='worksetupinmap',
            new_name='dashboard_w_workset_0897ac_idx',
            old_name='dashboard_w_worksetu_idx',
        ),
        migrations.AddField(
            model_name='batchplan',
            name='entity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
