# Generated by Django 6.0.6 on 2026-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_batchplan_naps_aligned_batchplan_nats_aligned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('candidate_count', models.IntegerField(default=0)),
                ('community_source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('community_category', models.CharField(blank=True, db_index=True, max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('spoc_name', models.CharField(blank=True, max_length=255)),
                ('spoc_contact', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['batch_id', 'community_source'], name='dashboard_s_batch_i_2573c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SourcingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('community_source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('community_category', models.CharField(blank=True, db_index=True, max_length=255)),
                ('target_count', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['batch_id', 'community_source'], name='dashboard_s_batch_i_0dc3d6_idx')],
            },
        ),
    ]
